coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - tests
        paths: 
          - "learnpdes"
        branches: 
          - main
        if_ci_failed: error
        informational: true
        only_pulls: true
    patch: off