# conda env create -f environment.yml

name: learnpdes
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - torchvision
  - torchaudio
  - pydantic
  - flask
  - sympy
  - requests
  - plotly
  - dash
  - imageio
  - networkx
  - fsspec
  - pillow
  - typing-extensions
  - pip:
      - coverage
      - torch
      - complexpytorch
      - flake8
      - narwhals
      - ambiance