name: Code quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Set up uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --locked --group docs

    - name: Run Ruff check
      run: uv run ruff check .

    - name: Check Ruff formatting
      run: uv run ruff format --check .

    - name: Check Python types
      run: uv run --group docs pyright

    - name: Check Python complexity
      run: uv run lizard -l python -C 12 -L 100 -a 14 -w learnpdes docs/website tests
