name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          auto-update-conda: true
          python-version: 3.12
          environment-file: environment.yml
          activate-environment: learnpdes

      - name: Run tests
        run: |
          python -m unittest discover -s . -p "*.py"

      - name: Run main script
        run: |
          python __main__.py