name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@d2e6a045a86077fb6cad6f5adf368e9076ddaa8d
        with:
          miniforge-variant: Miniforge3
          auto-update-conda: true
          miniforge-version: latest
          environment-file: environment.yml
          use-mamba: false
          activate-environment: learnpdes

      - name: Install learnpdes with pip
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          coverage run --source=learnpdes -m unittest discover -s learnpdes/model/tests -p "*.py"

      - name: Run test scenarios
        shell: bash -l {0}
        run: |
          coverage run --append --source=learnpdes -m unittest discover -s tests -p "test*.py"
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: tests
          fail_ci_if_error: true
          verbose: true